### ISSUE TITLE
help

### ISSUE THREAD

**Issue by omrih4** [Bram2323/MC-DeathSwap#1]
i wanna fork but no pom.xml or anything so it doesnt really work

**Comment by Bram2323** [comment]
This plugin was not made with maven so it doesn't need one. If you want to use this code you can copy paste it in your project

**Comment by omrih4** [comment]
I can't build tho bcuz the depenciies aren't included

**Comment by omrih4** [comment]
how did u add the deps then 
also thx for answering even tho this plugin is 2 years old 🙏

**Comment by Bram2323** [comment]
It looks like I loaded the api manually
I found this which hopefully helps: [Creating a blank spigot plugin](https://www.spigotmc.org/wiki/creating-a-blank-spigot-plugin-in-intellij-idea/)
And I think I got the spigot dependency using this: [BuildTools](https://www.spigotmc.org/wiki/buildtools/)

I actually made this plugin 5 years ago, so some things probably work different now.
Hopefully this helps tho!

**Comment by Bram2323** [comment]
It may be easier if you follow this tutorial [Creating a plugin with maven](https://www.spigotmc.org/wiki/creating-a-plugin-with-maven-using-intellij-idea/) and then copy paste the code
